# Generated by Django 3.0.8 on 2022-01-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolname', models.CharField(max_length=100)),
                ('schoollogo', models.ImageField(upload_to='static/schools')),
                ('schoolurl', models.URLField(blank=True)),
            ],
        ),
    ]
