# Generated by Django 3.0.8 on 2022-01-29 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schools',
            name='schoollogo',
            field=models.ImageField(upload_to='schools/images'),
        ),
    ]
