# Generated by Django 3.0.8 on 2022-01-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20220129_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolname', models.CharField(max_length=100)),
                ('schoollogo', models.ImageField(upload_to='school/images')),
                ('schoolurl', models.URLField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Schools',
        ),
    ]
