# Generated by Django 3.0.8 on 2022-01-29 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_auto_20220129_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='interest/images')),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
