# Generated by Django 3.0.8 on 2022-01-30 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_remove_social_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='email',
            field=models.EmailField(blank=True, max_length=100),
        ),
    ]
