# Generated by Django 3.0.8 on 2022-02-18 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0010_auto_20220217_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='schoollogo',
            field=models.URLField(blank=True),
        ),
    ]
